behaviors:
  JetRacerAgent:
    trainer_type: ppo
    max_steps: 10_000_000
    time_horizon: 512
    summary_freq: 50_000
    keep_checkpoints: 5
    hyperparameters:
      batch_size: 1024
      buffer_size: 8224
      learning_rate: 3e-4
      learning_rate_schedule: linear
      beta: 5e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
