behaviors:
  JetRacerAgent:
    trainer_type: ppo
    max_steps: 10_000_000
    time_horizon: 1500
    summary_freq: 50_000
    keep_checkpoints: 5
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3e-4
      beta: 5e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      vis_encode_type: simple
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
