behaviors:
  JetRacerAgent:
    trainer_type: ppo
    max_steps: 10_000_000
    time_horizon: 1500
    summary_freq: 50_000
    keep_checkpoints: 5
    hyperparameters:
      batch_size: 4096
      buffer_size: 32768
      learning_rate: 3e-4
      learning_rate_schedule: constant
      beta: 5e-3
      beta_schedule: constant
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
    network_settings:
      vis_encode_type: simple
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
